Update README.md
yunho0130/tensorflow-lite pull request #35
Opened 2020-08-12 14:49 UTC by dlqh406

list myname on the README.md

2020-08-12 15:17 UTC, yunho0130 requested changes
Please resolve branch conflicts. Update your local repo and PR again. @dlqh406

2020-08-12 15:24 UTC, dlqh406 commented
resolve conflict error

2020-08-13 05:59 UTC, yunho0130 requested changes
Please check the latest version of Readme.md. We changed the way to show contributor list due to word wrapping.

2020-08-13 11:38 UTC, yunho0130 approved these changes

2020-08-13 11:38 UTC, merged